apiVersion: apps/v1
kind: Deployment
metadata:
  name: evidently-ui
  namespace: evidently
  labels:
    app: evidently-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evidently-ui
  template:
    metadata:
      labels:
        app: evidently-ui
    spec:
      containers:
      - name: evidently-ui
        image: abisoye314/evidently-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "minio"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minio123"
        - name: AWS_ENDPOINT_URL
          value: "http://seaweedfs.kubeflow.svc.cluster.local:8333"
        - name: FSSPEC_S3_ENDPOINT_URL
          value: "http://seaweedfs.kubeflow.svc.cluster.local:8333"
        - name: FSSPEC_S3_KEY
          value: "minio"
        - name: FSSPEC_S3_SECRET
          value: "minio123"
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
