apiVersion: v1
kind: Service
metadata:
  name: evidently-ui
  namespace: evidently
  labels:
    app: evidently-ui
spec:
  type: ClusterIP
  selector:
    app: evidently-ui
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP