apiVersion: v1
kind: Service
metadata:
  labels:
    app: evidently-ui
  name: evidently-ui
  namespace: evidently
spec:
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: evidently-ui
  type: ClusterIP
