apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pvcviewer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/DurojaiyeAbisoye/k8s_mlops_repo.git
    targetRevision: master
    path: applications/notebooks-v1/upstream/pvcviewer-controller/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
