apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspaces-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/DurojaiyeAbisoye/k8s_mlops_repo.git
    targetRevision: master
    path: applications/workspaces/upstream/controller/overlays/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow-workspaces
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - /spec/preserveUnknownFields
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    jsonPointers:
      - /rules
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
